const storageKey = "passvault.web.credentials";
const state = { records: [], selectedId: null, query: "" };
const el = {
  totalCount: document.getElementById("totalCount"), weakCount: document.getElementById("weakCount"), reuseCount: document.getElementById("reuseCount"), searchInput: document.getElementById("searchInput"), exportButton: document.getElementById("exportButton"), importInput: document.getElementById("importInput"), newButton: document.getElementById("newButton"), form: document.getElementById("credentialForm"), recordId: document.getElementById("recordId"), siteInput: document.getElementById("siteInput"), usernameInput: document.getElementById("usernameInput"), passwordInput: document.getElementById("passwordInput"), lengthInput: document.getElementById("lengthInput"), memoInput: document.getElementById("memoInput"), togglePassword: document.getElementById("togglePassword"), generateButton: document.getElementById("generateButton"), deleteButton: document.getElementById("deleteButton"), status: document.getElementById("status"), accountTable: document.getElementById("accountTable"), emptyState: document.getElementById("emptyState")
};
function loadRecords(){try{const raw=localStorage.getItem(storageKey);state.records=raw?JSON.parse(raw):[]}catch{state.records=[];setStatus("저장 데이터를 읽지 못해 새 목록으로 시작했습니다.")}}
function saveRecords(){localStorage.setItem(storageKey,JSON.stringify(state.records))}
function setStatus(message){el.status.textContent=message}
function normalizeSite(site){return site.trim().replace(/^https?:\/\//,"").replace(/^www\./,"").replace(/\/.*$/,"").toLowerCase()}
function randomInt(max){const bucket=new Uint32Array(1);const limit=Math.floor(0xffffffff/max)*max;do{crypto.getRandomValues(bucket)}while(bucket[0]>=limit);return bucket[0]%max}
function generatePassword(length){const groups=["abcdefghijkmnopqrstuvwxyz","ABCDEFGHJKLMNPQRSTUVWXYZ","23456789","!@#$%^&*()-_=+[]{}"];const all=groups.join("");const chars=groups.map((group)=>group[randomInt(group.length)]);while(chars.length<length)chars.push(all[randomInt(all.length)]);for(let index=chars.length-1;index>0;index-=1){const swap=randomInt(index+1);const temp=chars[index];chars[index]=chars[swap];chars[swap]=temp}return chars.join("")}
function passwordScore(password){const classes=[/[a-z]/.test(password),/[A-Z]/.test(password),/\d/.test(password),/[^a-zA-Z0-9\s]/.test(password)].filter(Boolean).length;if(password.length<10||classes<3||/1234|password|qwerty/i.test(password))return"weak";if(password.length<14||classes<4)return"fair";return"strong"}
function duplicatePasswords(){const counts=new Map();state.records.forEach((record)=>{if(!record.password)return;counts.set(record.password,(counts.get(record.password)||0)+1)});return counts}
function filteredRecords(){const query=state.query.trim().toLowerCase();if(!query)return state.records;return state.records.filter((record)=>[record.site,record.username,record.memo].join(" ").toLowerCase().includes(query))}
function formatDate(value){if(!value)return"-";return new Intl.DateTimeFormat("ko-KR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
function statusBadge(record,duplicates){if(duplicates.get(record.password)>1)return'<span class="badge danger">중복</span>';const score=passwordScore(record.password||"");if(score==="weak")return'<span class="badge danger">약함</span>';if(score==="fair")return'<span class="badge warning">보통</span>';return'<span class="badge">강함</span>'}
function escapeHtml(value){return String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function render(){const duplicates=duplicatePasswords();const weakCount=state.records.filter((record)=>passwordScore(record.password||"")==="weak").length;const reuseCount=state.records.filter((record)=>duplicates.get(record.password)>1).length;el.totalCount.textContent=String(state.records.length);el.weakCount.textContent=String(weakCount);el.reuseCount.textContent=String(reuseCount);const rows=filteredRecords();el.accountTable.innerHTML=rows.map((record)=>`<tr data-id="${record.id}"><td><div class="site-cell">${escapeHtml(record.site)}</div><div class="muted">${escapeHtml(record.memo||"")}</div></td><td>${escapeHtml(record.username)}</td><td>${statusBadge(record,duplicates)}</td><td class="muted">${formatDate(record.updatedAt)}</td></tr>`).join("");el.emptyState.classList.toggle("visible",rows.length===0)}
function resetForm(){state.selectedId=null;el.recordId.value="";el.siteInput.value="";el.usernameInput.value="";el.passwordInput.value="";el.memoInput.value="";el.siteInput.focus();setStatus("새 계정을 입력하세요.")}
function selectRecord(id){const record=state.records.find((item)=>item.id===id);if(!record)return;state.selectedId=id;el.recordId.value=record.id;el.siteInput.value=record.site;el.usernameInput.value=record.username;el.passwordInput.value=record.password;el.memoInput.value=record.memo||"";setStatus(`${record.site} 계정을 편집 중입니다.`)}
function upsertRecord(event){event.preventDefault();const now=new Date().toISOString();const record={id:el.recordId.value||crypto.randomUUID(),site:normalizeSite(el.siteInput.value),username:el.usernameInput.value.trim(),password:el.passwordInput.value,memo:el.memoInput.value.trim(),updatedAt:now};if(!record.site||!record.username||!record.password){setStatus("사이트, 아이디, 비밀번호를 모두 입력하세요.");return}const index=state.records.findIndex((item)=>item.id===record.id);if(index>=0){state.records[index]=record}else{state.records.unshift(record)}state.selectedId=record.id;saveRecords();render();selectRecord(record.id);setStatus("저장했습니다.")}
function deleteSelected(){if(!state.selectedId){resetForm();return}state.records=state.records.filter((record)=>record.id!==state.selectedId);saveRecords();render();resetForm();setStatus("삭제했습니다.")}
function exportRecords(){const payload=JSON.stringify({exportedAt:new Date().toISOString(),records:state.records},null,2);const blob=new Blob([payload],{type:"application/json"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download="passvault-ids.json";link.click();URL.revokeObjectURL(url);setStatus("JSON 파일로 내보냈습니다.")}
function importRecords(file){if(!file)return;const reader=new FileReader();reader.addEventListener("load",()=>{try{const parsed=JSON.parse(String(reader.result));const records=Array.isArray(parsed)?parsed:parsed.records;if(!Array.isArray(records))throw new Error("Invalid format");state.records=records.map((record)=>({id:record.id||crypto.randomUUID(),site:normalizeSite(record.site||""),username:String(record.username||"").trim(),password:String(record.password||""),memo:String(record.memo||"").trim(),updatedAt:record.updatedAt||new Date().toISOString()})).filter((record)=>record.site&&record.username&&record.password);saveRecords();render();resetForm();setStatus("가져오기를 완료했습니다.")}catch{setStatus("가져오기 파일을 읽지 못했습니다.")}});reader.readAsText(file)}
el.form.addEventListener("submit",upsertRecord);el.newButton.addEventListener("click",resetForm);el.deleteButton.addEventListener("click",deleteSelected);el.exportButton.addEventListener("click",exportRecords);el.importInput.addEventListener("change",(event)=>importRecords(event.target.files[0]));el.searchInput.addEventListener("input",(event)=>{state.query=event.target.value;render()});el.generateButton.addEventListener("click",()=>{const length=Math.max(12,Math.min(128,Number(el.lengthInput.value)||20));el.lengthInput.value=String(length);el.passwordInput.value=generatePassword(length);setStatus("강한 비밀번호를 생성했습니다.")});el.togglePassword.addEventListener("click",()=>{const visible=el.passwordInput.type==="text";el.passwordInput.type=visible?"password":"text";el.togglePassword.textContent=visible?"보기":"숨김"});el.accountTable.addEventListener("click",(event)=>{const row=event.target.closest("tr[data-id]");if(row)selectRecord(row.dataset.id)});
loadRecords();render();
